/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gpbdSxslyqS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useMemo } from "react"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuCheckboxItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"

export function ProductList() {
  const products = [
    {
      id: 1,
      name: "Wireless Headphones",
      description: "High-quality sound with noise cancellation",
      price: 99.99,
      image: "/placeholder.svg",
    },
    {
      id: 2,
      name: "Leather Backpack",
      description: "Durable and stylish everyday bag",
      price: 149.99,
      image: "/placeholder.svg",
    },
    {
      id: 3,
      name: "Smartwatch",
      description: "Track your fitness and stay connected",
      price: 199.99,
      image: "/placeholder.svg",
    },
    {
      id: 4,
      name: "Portable Bluetooth Speaker",
      description: "Powerful sound in a compact design",
      price: 79.99,
      image: "/placeholder.svg",
    },
    {
      id: 5,
      name: "Ergonomic Office Chair",
      description: "Comfortable and supportive for long hours",
      price: 299.99,
      image: "/placeholder.svg",
    },
    {
      id: 6,
      name: "Outdoor Camping Gear",
      description: "Essential equipment for your next adventure",
      price: 149.99,
      image: "/placeholder.svg",
    },
  ]
  const [sortBy, setSortBy] = useState("featured")
  const [filterBy, setFilterBy] = useState([])
  const handleSortChange = (value) => {
    setSortBy(value)
  }
  const handleFilterChange = (value) => {
    if (filterBy.includes(value)) {
      setFilterBy(filterBy.filter((item) => item !== value))
    } else {
      setFilterBy([...filterBy, value])
    }
  }
  const filteredProducts = useMemo(() => {
    return products
      .filter((product) => {
        if (filterBy.length === 0) return true
        return filterBy.includes(product.category)
      })
      .sort((a, b) => {
        switch (sortBy) {
          case "featured":
            return b.featured - a.featured
          case "low":
            return a.price - b.price
          case "high":
            return b.price - a.price
          case "newest":
            return new Date(b.date) - new Date(a.date)
          default:
            return 0
        }
      })
  }, [products, sortBy, filterBy])
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">Products</h1>
        <div className="flex items-center gap-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">
                <ArrowUpDownIcon className="w-4 h-4 mr-2" />
                Sort by: {sortBy}
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent className="w-[200px]" align="end">
              <DropdownMenuRadioGroup value={sortBy} onValueChange={handleSortChange}>
                <DropdownMenuRadioItem value="featured">Featured</DropdownMenuRadioItem>
                <DropdownMenuRadioItem value="low">Price: Low to High</DropdownMenuRadioItem>
                <DropdownMenuRadioItem value="high">Price: High to Low</DropdownMenuRadioItem>
                <DropdownMenuRadioItem value="newest">Newest</DropdownMenuRadioItem>
              </DropdownMenuRadioGroup>
            </DropdownMenuContent>
          </DropdownMenu>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">
                <FilterIcon className="w-4 h-4 mr-2" />
                Filters
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent className="w-[200px]" align="end">
              <DropdownMenuCheckboxItem
                checked={filterBy.includes("electronics")}
                onCheckedChange={() => handleFilterChange("electronics")}
              >
                Electronics
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filterBy.includes("apparel")}
                onCheckedChange={() => handleFilterChange("apparel")}
              >
                Apparel
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filterBy.includes("home")}
                onCheckedChange={() => handleFilterChange("home")}
              >
                Home
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filterBy.includes("outdoor")}
                onCheckedChange={() => handleFilterChange("outdoor")}
              >
                Outdoor
              </DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {filteredProducts.map((product) => (
          <div key={product.id} className="bg-background rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt={product.name}
              width={400}
              height={300}
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">{product.name}</h3>
              <p className="text-muted-foreground">{product.description}</p>
              <div className="flex justify-between items-center mt-4">
                <span className="text-primary font-semibold">${product.price}</span>
                <Button size="sm">Add to Cart</Button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function ArrowUpDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
    </svg>
  )
}


function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}
