import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import { Navbar } from "@/components/component/navbar";
import { Footer } from "@/components/component/footer";
import { CartProvider } from "./cartcontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by InnovateX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <CartProvider>
          <body className={inter.className}>
            <Navbar />
            <div className="flex flex-col min-h-screen">
              {children}
            </div>
            <Footer />
          </body>
        </CartProvider>
      </Providers>
    </html>
  );
}
